context:
  name: autogen-agentchat
  version: "0.6.4"
  python_min: "3.10"
  
package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autogen_agentchat-{{ version }}.tar.gz
  sha256: e8fadd6c18b7423551cb7ba81b4e7c570b60a12cf904d839be11070ef270e89f

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }},<3.13
    - autogen-core =0.6.4

tests:
  - python:
      imports:
      - autogen
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://microsoft.github.io/autogen
  summary: 'Enabling Next-Gen LLM Applications via Multi-Agent Conversation Framework'
  license: Apache-2.0 AND EPL-2.0 AND MIT
  license_file:
    - LICENSE-CODE-KUBERNETES
    - LICENSE-CODE
    - LICENSE
  documentation: https://microsoft.github.io/autogen
  repository: https://github.com/microsoft/autogen

extra:
  recipe-maintainers:
    - raybellwaves
    - jan-janssen
