context:
  name: autogen-agentchat
  version: "0.4.2"
  python_min: "3.8"
package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 00634e7fbb6b8e922b44cea1b6632c7afdf6a285ed4a14dc84386b0669410c1c

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=${{ python_min }},<3.13
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<3.13
    - openai >=1.3
    - diskcache
    - termcolor
    - flaml
    - numpy >=1.17.0,<2
    - python-dotenv
    - tiktoken
    - pydantic >=1.10,<3,!=2.6.0
    - docker-py
    - packaging

tests:
  - python:
      imports:
        - autogen
      pip_check: true

about:
  homepage: https://microsoft.github.io/autogen
  summary: 'Enabling Next-Gen LLM Applications via Multi-Agent Conversation Framework'
  license: Apache-2.0 AND EPL-2.0 AND MIT
  license_file:
    - LICENSE-CODE-KUBERNETES
    - LICENSE-CODE
    - LICENSE
  documentation: https://microsoft.github.io/autogen
  repository: https://github.com/microsoft/autogen

extra:
  recipe-maintainers:
    - raybellwaves
